#!/usr/bin/env python3
"""Generate 28 per-config YAMLs and sbatch scripts for the CR3-on-Nemotron sweep.

Walks every CR3 TOML under cosmos-reason2/examples/cosmos_rl/configs/cr3-8b/
and emits, for each:

  Nemotron/src/nemotron/recipes/omni3/stage0_sft/config/cr3/<ds>/<run>.yaml
      thin override on top of cr3_base.yaml (extends:) — sets
      checkpoint.save / dataset.path / train.train_iters / optimizer.lr
      from the CR3 TOML (epoch + optm_lr).

  cr3-nemotron/sbatch/<ds>/sbatch_<run>.sh
      timeout-and-requeue COMMANDS-array sbatch. Mirrors the resume pattern
      in cosmos-reason2/cr3_assy17/sbatch_assy17.sh, but launches via
      torchrun + the omni3-sft container instead of cosmos-rl.

Usage:
    python gen_cr3_configs.py \\
        --cr3-tomls-dir cosmos-reason2/examples/cosmos_rl/configs/cr3-8b \\
        --energon-root  /lustre/fsw/.../chrislin/datasets/cr3-nemotron/energon \\
        --out-yaml-dir  Nemotron/src/nemotron/recipes/omni3/stage0_sft/config/cr3 \\
        --out-sbatch-dir cr3-nemotron/sbatch \\
        --ckpt-root     /lustre/fsw/.../chrislin/cr3-nemotron/ckpt
"""

from __future__ import annotations

import argparse
import os
import stat
import tomllib
from pathlib import Path

# 28 configs in CR3 (4 datasets × 7 each); mark which datasets are 30-epoch
LONG_EPOCH_DATASETS = {"tp00303"}

YAML_TEMPLATE = """# AUTO-GENERATED by Nemotron/cr3/scripts/gen_cr3_configs.py
# Source CR3 TOML: {source_toml}
# Run: {run_name}    Dataset: {dataset}
# epoch={epoch}  lm_lr={lm_lr}  train_iters={train_iters}

defaults:
  - cr3_base   # extends Nemotron/.../config/cr3_base.yaml

run:
  name: cr3-nemotron-{run_name}

train:
  train_iters: {train_iters}
  optimizer:
    lr: {lm_lr}
"""

SBATCH_TEMPLATE = r"""#!/bin/bash
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --time=04:00:00
#SBATCH --mem=0
#SBATCH --overcommit
#SBATCH --dependency=singleton
#SBATCH --exclusive
#SBATCH --nodes=1
#SBATCH --gpus-per-node=8
#SBATCH --cpus-per-task=32
#SBATCH --job-name={job_name}
#SBATCH --output=./logs/%x-%j/stdout.log
#SBATCH --error=./logs/%x-%j/stderr.log

# Auto-resume across 4-hour wall-clock windows. Each entry runs one
# 4-hour window of training; scontrol requeue picks up the next one.
# The number of entries here equals ceil(epochs / windows_per_epoch);
# adjust if you change train_iters / global_batch_size in the YAML.
COMMANDS=(
{commands}
)

INDEX_FILE="${{SLURM_LOG_DIR:-${{HOME}}/slurm-logs}}/${{SLURM_JOB_NAME}}-${{SLURM_JOB_ID}}_command_index.txt"
mkdir -p "$(dirname $INDEX_FILE)"

if [[ ! -f $INDEX_FILE ]]; then
    CURRENT_INDEX=0
    echo "0" > "$INDEX_FILE"
else
    CURRENT_INDEX=$(cat "$INDEX_FILE")
fi

if [[ $CURRENT_INDEX -ge ${{#COMMANDS[@]}} ]]; then
    echo "All commands processed. Exiting."
    exit 0
fi

CURRENT_COMMAND=${{COMMANDS[$CURRENT_INDEX]}}
echo "[wave $((CURRENT_INDEX+1))/${{#COMMANDS[@]}}] $CURRENT_COMMAND"

# All paths come from env-setup.sh — sbatch inherits the submitter's env.
# If you submit without sourcing env-setup.sh first, override these on the
# sbatch command line via --export=ALL,VAR=val,...
SQSH="${{OMNI3_SFT_SQSH:-/lustre/fsw/portfolios/edgeai/users/$USER/.cache/nemotron/containers/omni3-sft.sqsh}}"
NEMOTRON_ROOT="{nemotron_root}"
CR_ROOT="$(cd "$NEMOTRON_ROOT/.." && pwd)"

MOUNTS="$HOME:/root,/lustre:/lustre,$NEMOTRON_ROOT:/workspace/Nemotron"
[[ -d "$CR_ROOT/cosmos-reason2" ]] && MOUNTS="$MOUNTS,$CR_ROOT/cosmos-reason2:/workspace/cosmos-reason2"

timeout 3.95h srun \
    --container-image="$SQSH" \
    --container-mounts="$MOUNTS" \
    --container-writable \
    bash -c "
set -e
export OMNI3_MEGATRON_CHECKPOINT='{megatron_ckpt}'
export CR3_ENERGON_PATH='{energon_path}'
export CR3_CKPT_SAVE='{ckpt_save}'
export CR3_TRAIN_ITERS='{train_iters}'
export CR3_LM_LR='{lm_lr}'
export PYTORCH_ALLOC_CONF=expandable_segments:True
unset SSL_CERT_FILE SSL_CERT_DIR XDG_RUNTIME_DIR

cd /workspace/Nemotron/src/nemotron/recipes/omni3/stage0_sft
echo 'Starting omni3 SFT for run: {run_name}'
torchrun --nproc-per-node=8 train.py \
    --config /workspace/Nemotron/src/nemotron/recipes/omni3/stage0_sft/config/cr3/{dataset}/{run_name}.yaml
"

CURRENT_INDEX=$((CURRENT_INDEX + 1))
echo $CURRENT_INDEX > "$INDEX_FILE"

if [[ $CURRENT_INDEX -lt ${{#COMMANDS[@]}} ]]; then
    echo "Requeuing for next 4-hour window..."
    scontrol requeue $SLURM_JOB_ID
else
    echo "All windows finished."
fi
"""


def parse_cr3_toml(toml_path: Path) -> dict:
    """Pull the per-run knobs we need from a CR3 TOML."""
    with open(toml_path, "rb") as f:
        cfg = tomllib.load(f)
    train = cfg.get("train", {})
    epoch = int(train.get("epoch", 10))
    lr_list = train.get("optm_lr", [1.5e-5, 1e-6, 1.5e-5])
    # CR3 stores per-component LRs as [llm, vlm, linear]; we only train the
    # LM at the end (vision frozen via cr3_base.yaml), so use the LM LR.
    lm_lr = float(lr_list[0]) if lr_list else 1.5e-5
    return {"epoch": epoch, "lm_lr": lm_lr}


def estimate_train_iters(epoch: int, dataset: str) -> int:
    """Rough train_iters from epoch count.

    CR3 uses dataset-specific epoch counts (10 for most, 30 for tp00303).
    Without knowing the exact sample count yet, use a conservative
    iters-per-epoch estimate that the user can override later via the
    CR3_TRAIN_ITERS env var.
    """
    iters_per_epoch = 400  # ~400 iters/epoch at gbs=32 for ASSY17-sized datasets
    return iters_per_epoch * epoch


def num_resume_windows(epoch: int, dataset: str) -> int:
    """How many 4-hour windows the job needs to fit train_iters."""
    if dataset in LONG_EPOCH_DATASETS or epoch >= 30:
        return 8
    return 4


def write_yaml(out_path: Path, source_toml: Path, run_name: str, dataset: str,
               epoch: int, lm_lr: float, train_iters: int) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(YAML_TEMPLATE.format(
        source_toml=source_toml,
        run_name=run_name,
        dataset=dataset,
        epoch=epoch,
        lm_lr=f"{lm_lr:g}",
        train_iters=train_iters,
    ))


def write_sbatch(out_path: Path, run_name: str, dataset: str,
                 num_windows: int, energon_path: Path, ckpt_save: Path,
                 megatron_ckpt: str, train_iters: int, lm_lr: float,
                 nemotron_root: Path, account: str, partition: str) -> None:
    cmd_line = f'    "torchrun-omni3-sft"'   # placeholder — actual command embedded in srun bash above
    commands = "\n".join([cmd_line] * num_windows)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(SBATCH_TEMPLATE.format(
        commands=commands,
        job_name=f"cr3-nemotron-{run_name}".replace("_", "-"),
        nemotron_root=nemotron_root,
        account=account,
        partition=partition,
        megatron_ckpt=megatron_ckpt,
        energon_path=energon_path,
        ckpt_save=ckpt_save,
        train_iters=train_iters,
        lm_lr=f"{lm_lr:g}",
        run_name=run_name,
        dataset=dataset,
    ))
    out_path.chmod(out_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)


def main() -> int:
    # Default the Nemotron repo root to ../.. relative to this script (script
    # lives at <Nemotron>/cr3/scripts/gen_cr3_configs.py) so the script Just
    # Works after the merge, regardless of which user is running it.
    DEFAULT_NEMOTRON_ROOT = Path(__file__).resolve().parents[2]

    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--cr3-tomls-dir", type=Path, required=True,
                    help="cosmos-reason2/examples/cosmos_rl/configs/cr3-8b")
    ap.add_argument("--energon-root", type=Path, required=True,
                    help="root of converted Energon datasets "
                         "(<root>/<ds>/<run-name>/.nv-meta/...)")
    ap.add_argument("--out-yaml-dir", type=Path,
                    default=DEFAULT_NEMOTRON_ROOT / "src/nemotron/recipes/omni3/stage0_sft/config/cr3",
                    help="Where the per-run YAMLs land "
                         "(defaults to <Nemotron>/src/nemotron/recipes/omni3/stage0_sft/config/cr3)")
    ap.add_argument("--out-sbatch-dir", type=Path,
                    default=DEFAULT_NEMOTRON_ROOT / "cr3" / "sbatch",
                    help="Where the per-run sbatch files land "
                         "(defaults to <Nemotron>/cr3/sbatch)")
    ap.add_argument("--ckpt-root", type=Path, required=True,
                    help="root for Megatron checkpoints (per-run subdirs)")
    ap.add_argument("--megatron-ckpt-env",
                    default="${OMNI3_MEGATRON_CHECKPOINT}",
                    help="Pretrain checkpoint path (env-var expansion left in "
                         "the sbatch so each user inherits OMNI3_MEGATRON_CHECKPOINT "
                         "from env-setup.sh)")
    ap.add_argument("--nemotron-root", type=Path, default=DEFAULT_NEMOTRON_ROOT,
                    help="Path to the Nemotron repo root, used in the sbatch "
                         "container_mounts so /workspace/Nemotron resolves "
                         "(defaults to grandparent of this script)")
    ap.add_argument("--account", type=str,
                    default="edgeai_tao-ptm_image-foundation-model-clip",
                    help="Slurm account billed for training jobs")
    ap.add_argument("--partition", type=str,
                    default="polar4,polar3,polar,batch_block1,grizzly,batch_block2,batch_block3",
                    help="Comma-separated partition list")
    args = ap.parse_args()

    src_root: Path = args.cr3_tomls_dir.resolve()
    yaml_root: Path = args.out_yaml_dir.resolve()
    sbatch_root: Path = args.out_sbatch_dir.resolve()
    energon_root: Path = args.energon_root.resolve()
    ckpt_root: Path = args.ckpt_root.resolve()

    tomls = sorted(src_root.rglob("*.toml"))
    if not tomls:
        print(f"ERROR: no TOMLs under {src_root}")
        return 1

    print(f"Found {len(tomls)} CR3 TOMLs")
    for toml_path in tomls:
        dataset = toml_path.parent.name
        run_name = toml_path.stem
        knobs = parse_cr3_toml(toml_path)
        train_iters = estimate_train_iters(knobs["epoch"], dataset)
        windows = num_resume_windows(knobs["epoch"], dataset)

        yaml_path = yaml_root / dataset / f"{run_name}.yaml"
        sbatch_path = sbatch_root / dataset / f"sbatch_{run_name}.sh"
        energon_path = energon_root / dataset / run_name
        ckpt_save = ckpt_root / dataset / run_name

        write_yaml(yaml_path, toml_path, run_name, dataset,
                   knobs["epoch"], knobs["lm_lr"], train_iters)
        write_sbatch(sbatch_path, run_name, dataset, windows,
                     energon_path, ckpt_save, args.megatron_ckpt_env,
                     train_iters, knobs["lm_lr"],
                     args.nemotron_root, args.account, args.partition)

        print(f"[{dataset}/{run_name}] yaml={yaml_path.relative_to(args.out_yaml_dir.parent.parent.parent.parent.parent if False else yaml_root.parent)} "
              f"sbatch={sbatch_path.name} epoch={knobs['epoch']} "
              f"lm_lr={knobs['lm_lr']:g} iters={train_iters} windows={windows}")

    print(f"\nDone: {len(tomls)} YAMLs + {len(tomls)} sbatch files written.")
    print(f"  YAMLs:   {yaml_root}")
    print(f"  Sbatch:  {sbatch_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
